// Copies the pure exam-grading modules into the Edge Functions tree so the
// server grades with exactly the code the app uses.
//   node scripts/edgeGrading.mjs          write the copies
//   node scripts/edgeGrading.mjs --check  exit 1 when they are stale
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
export const FRONTEND = resolve(here, "..");
export const SOURCE_DIR = join(FRONTEND, "src/shared/domain/exam");
export const TARGET_DIR = resolve(FRONTEND, "../backend/supabase/functions/_shared/exam");
export const MODULES = ["questionKind", "scoring", "sections", "paperBuilder", "autoGrade", "phase", "release"];

const HEADER = "// GENERATED by frontend/scripts/edgeGrading.mjs from src/shared/domain/exam. Do not edit.\n";

const TYPES = `${HEADER}export type { PaperSlot } from "./paperBuilder.ts";

export type DBQuestion = {
  id: string;
  exam_id: string | null;
  title: string;
  type: string;
  unit: string | null;
  difficulty: string | null;
  marks: number;
  options: string[] | null;
  answer: string | null;
  subjective_mode?: "both" | "qr" | "textbox" | null;
};
`;

export function transform(src) {
  return HEADER + src
    .replace(/from "@\/shared\/data\/(examApi|api\/types)"/g, 'from "./types.ts"')
    .replace(/from "\.\/([A-Za-z]+)"/g, 'from "./$1.ts"');
}

export function buildFiles() {
  const files = { "types.ts": TYPES };
  for (const m of MODULES) files[`${m}.ts`] = transform(readFileSync(join(SOURCE_DIR, `${m}.ts`), "utf8"));
  return files;
}

export function staleFiles() {
  return Object.entries(buildFiles())
    .filter(([name, body]) => {
      const p = join(TARGET_DIR, name);
      return !existsSync(p) || readFileSync(p, "utf8") !== body;
    })
    .map(([name]) => name);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.includes("--check")) {
    const stale = staleFiles();
    if (stale.length) {
      console.error(`Edge grading copies are stale: ${stale.join(", ")}. Run: node scripts/edgeGrading.mjs`);
      process.exit(1);
    }
  } else {
    mkdirSync(TARGET_DIR, { recursive: true });
    for (const [name, body] of Object.entries(buildFiles())) writeFileSync(join(TARGET_DIR, name), body);
    console.log(`Wrote ${MODULES.length + 1} files to ${TARGET_DIR}`);
  }
}
