import { useState } from "react";

type Props = { notify: (message: string) => void; navigate: (path: string) => void };
const formats = ["MCQ", "MSQ", "True / False", "Numerical", "Subjective", "Coding"];
const fieldClass = "mt-1 block w-full border border-line-strong bg-paper px-3 py-2.5 text-[13px] outline-none focus:border-forest";

export default function QuestionEditorV3({ notify, navigate }: Props) {
  const [format, setFormat] = useState("MCQ");
  const [prompt, setPrompt] = useState("");
  const [options, setOptions] = useState(["", "", "", ""]);
  const [unit, setUnit] = useState("Trees & Graphs");
  const [customUnit, setCustomUnit] = useState("");
  const [negative, setNegative] = useState("");
  const [saved, setSaved] = useState(false);
  const choice = format === "MCQ" || format === "MSQ";
  const updateOption = (i: number, value: string) => setOptions((items) => items.map((item, index) => index === i ? value : item));
  const save = () => { if (prompt.trim() && (!choice || options.filter(Boolean).length >= 2) && (unit !== "Custom / Other" || customUnit.trim())) { setSaved(true); notify("Question saved"); } };
  return <div><div className="flex items-end justify-between gap-5"><div><p className="font-mono text-[10px] uppercase tracking-widest text-ink-soft">Question bank / New question</p><h1 className="mt-2 font-serif text-3xl font-semibold">Create a question</h1><p className="mt-2 text-[13px] text-ink-soft">The form adapts to each answer format so nothing important is missed.</p></div><button onClick={() => navigate("/teacher/questions")} className="font-mono text-[10px] uppercase tracking-wider text-ink-soft">← Back</button></div>
    <div className="mt-8 grid gap-8 xl:grid-cols-[1fr_330px]"><div className="space-y-6"><section className="border border-line bg-paper p-6"><p className="font-mono text-[10px] uppercase tracking-widest text-ink-soft">1 · Answer format</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{formats.map((item) => <button key={item} onClick={() => setFormat(item)} className={`border px-3 py-3 text-left text-[12px] ${format === item ? "border-forest bg-success/5 text-forest" : "border-line-strong text-ink-soft"}`}><span className="block font-medium">{item}</span><span className="mt-1 block text-[10px]">{formatHint(item)}</span></button>)}</div></section>
      <section className="border border-line bg-paper p-6"><p className="font-mono text-[10px] uppercase tracking-widest text-ink-soft">2 · Question content</p><label className="mt-4 block text-[12px] text-ink-soft">Prompt <span className="text-alert">*</span><textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} rows={5} placeholder="Write the complete question…" className={`${fieldClass} resize-y text-[14px]`}/></label><FormatFields format={format} options={options} updateOption={updateOption}/></section>
      <section className="border border-line bg-paper p-6"><p className="font-mono text-[10px] uppercase tracking-widest text-ink-soft">3 · Scoring and organization</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="block text-[12px] text-ink-soft">Unit<select value={unit} onChange={(e) => setUnit(e.target.value)} className={fieldClass}><option>Trees &amp; Graphs</option><option>Normalization</option><option>Sorting</option><option>OS Scheduling</option><option>Networking</option><option>Custom / Other</option></select>{unit === "Custom / Other" && <input value={customUnit} onChange={(e) => setCustomUnit(e.target.value)} placeholder="Enter custom unit name" className={`${fieldClass} border-forest`}/>}</label><Select label="Difficulty" options={["Easy", "Medium", "Hard"]}/><label className="block text-[12px] text-ink-soft">Marks<input type="number" defaultValue="1" min="0" step="0.5" className={fieldClass}/></label><label className="block text-[12px] text-ink-soft">Negative marking<input value={negative} onChange={(e) => setNegative(e.target.value)} placeholder="Enter value or leave blank" className={fieldClass}/><span className="mt-1 block text-[10px] text-ink-soft">Example: 0.25 marks deducted for an incorrect answer.</span></label></div><label className="mt-5 block text-[12px] text-ink-soft">Explanation / solution<textarea rows={3} placeholder="Optional explanation for review…" className={`${fieldClass} resize-y`}/></label><label className="mt-5 block text-[12px] text-ink-soft">Tags<input placeholder="trees, traversal, midterm" className={fieldClass}/></label></section></div>
      <aside className="space-y-5"><section className="sticky top-24 border border-line bg-paper-raised p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-ink-soft">Student preview</p><div className="mt-4 border border-line bg-paper p-4"><p className="font-mono text-[10px] text-ink-soft">Question 01 · {format}</p><p className="mt-3 text-[13px] leading-relaxed">{prompt || "Your question prompt will appear here."}</p><PreviewFields format={format} options={options}/></div><div className="mt-5 space-y-3 text-[12px]"><p className={prompt.trim() ? "text-success" : "text-alert"}>{prompt.trim() ? "✓" : "○"} Prompt added</p><p className={choice && options.filter(Boolean).length < 2 ? "text-alert" : "text-success"}>{choice && options.filter(Boolean).length < 2 ? "○" : "✓"} Answer format complete</p><p className={unit === "Custom / Other" && !customUnit.trim() ? "text-alert" : "text-success"}>{unit === "Custom / Other" && !customUnit.trim() ? "○" : "✓"} Unit assigned</p><p className="text-success">✓ Scoring ready</p></div></section><section className="border border-line p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-ink-soft">Save question</p><p className="mt-2 text-[12px] text-ink-soft">Save it to reuse in future exams.</p><button onClick={save} className="mt-4 w-full border border-forest bg-forest py-2.5 font-mono text-[10px] uppercase tracking-wider text-paper">Save to question bank</button>{saved && <p className="mt-4 text-[12px] text-success">Question saved successfully.</p>}</section></aside></div></div>;
}

function FormatFields({ format, options, updateOption }: { format: string; options: string[]; updateOption: (i: number, value: string) => void }) { if (format === "MCQ" || format === "MSQ") return <div className="mt-5"><p className="text-[12px] text-ink-soft">{format === "MSQ" ? "Options · select all correct answers" : "Options · select one correct answer"}</p><div className="mt-2 space-y-2">{options.map((option, i) => <div key={i} className="flex gap-2"><input type={format === "MSQ" ? "checkbox" : "radio"} name="correct" className="mt-3 accent-forest"/><input value={option} onChange={(e) => updateOption(i, e.target.value)} placeholder={`Option ${String.fromCharCode(65 + i)}`} className="flex-1 border border-line-strong bg-paper px-3 py-2.5 text-[13px]"/></div>)}</div><button onClick={() => updateOption(options.length, "")} className="mt-3 font-mono text-[10px] uppercase text-forest">+ Add option</button></div>; if (format === "True / False") return <div className="mt-5 grid grid-cols-2 gap-3"><button className="border border-line p-4 text-left text-[13px]">○ True</button><button className="border border-line p-4 text-left text-[13px]">○ False</button></div>; if (format === "Numerical") return <label className="mt-5 block text-[12px] text-ink-soft">Correct answer<input placeholder="e.g. 42 or 3.14" className={fieldClass}/><span className="mt-1 block text-[10px]">Optional tolerance can be set in the exam.</span></label>; if (format === "Subjective") return <div className="mt-5 border-l-2 border-amber bg-amber/5 px-3 py-3 text-[12px] text-ink-soft">Students receive a written response area. Add grading guidance in the explanation field below.</div>; return <div className="mt-5 grid gap-4"><label className="text-[12px] text-ink-soft">Input, output, and constraints<textarea rows={3} placeholder="Describe the problem and constraints…" className={fieldClass}/></label><div className="grid gap-4 sm:grid-cols-2"><Select label="Language" options={["Any language", "C", "C++", "Java", "Python"]}/><Select label="Time limit" options={["1 second", "2 seconds", "5 seconds"]}/></div></div>; }
function PreviewFields({ format, options }: { format: string; options: string[] }) { if (format === "MCQ" || format === "MSQ") return <div className="mt-4 space-y-2">{options.filter(Boolean).map((option, i) => <div key={option + i} className="border border-line px-3 py-2 text-[12px]">○ {option}</div>)}</div>; if (format === "Coding") return <div className="mt-4 h-16 border border-dashed border-line-strong p-3 font-mono text-[10px] text-ink-soft">Code editor area</div>; return <div className="mt-4 border border-dashed border-line-strong p-3 text-[11px] text-ink-soft">Student answer area</div>; }
function Select({ label, options }: { label: string; options: string[] }) { return <label className="block text-[12px] text-ink-soft">{label}<select className={fieldClass}>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function formatHint(format: string) { return format === "MCQ" ? "One correct answer" : format === "MSQ" ? "Many correct answers" : format === "Coding" ? "Code submission" : format === "Numerical" ? "Number answer" : format === "Subjective" ? "Written response" : "Binary answer"; }
