import { Link } from "react-router-dom";
import RoleLayout from "../components/RoleLayout";

const nav = [{ label: "Overview", to: "/student", end: true }, { label: "My exams", to: "/student/exams" }, { label: "Results", to: "/student/results" }, { label: "Help & support", to: "/student/help" }];
const upcoming = [{ name: "Data Structures & Algorithms", meta: "CSE · Semester III · 45 minutes", date: "Today · 10:00 AM", ready: true }, { name: "Digital Electronics", meta: "ECE · Semester III · 60 minutes", date: "18 Mar 2026 · 2:00 PM", ready: false }];

export default function StudentHome() {
  return <RoleLayout role="Student" name="Priya Nikitha" subtitle="21VGN0142 · CSE — Sem III" tone="#7A1F2B" items={nav}>
    <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] uppercase tracking-widest text-ink-soft">Student dashboard</p><h1 className="mt-2 font-serif text-3xl font-semibold">Good morning, Priya.</h1><p className="mt-2 text-[13px] text-ink-soft">Your next assessment is ready when you are.</p></div><span className="border border-success/40 bg-success/5 px-3 py-2 font-mono text-[10px] uppercase tracking-wider text-success">Profile verified</span></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="border border-line bg-paper-raised p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-ink-soft">Upcoming</p><p className="mt-2 font-serif text-3xl">2</p><p className="mt-1 text-[12px] text-ink-soft">scheduled exams</p></div><div className="border border-line bg-paper-raised p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-ink-soft">Completed</p><p className="mt-2 font-serif text-3xl">8</p><p className="mt-1 text-[12px] text-ink-soft">assessments this term</p></div><div className="border border-line bg-paper-raised p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-ink-soft">Average score</p><p className="mt-2 font-serif text-3xl">78%</p><p className="mt-1 text-[12px] text-ink-soft">across published results</p></div></div>
    <section className="mt-9"><div className="flex items-center justify-between"><h2 className="font-serif text-xl font-semibold">Your exam schedule</h2><Link to="/student/exams" className="font-mono text-[10px] uppercase tracking-wider text-ink-soft hover:text-ink">View all →</Link></div><div className="mt-3 space-y-2">{upcoming.map((exam) => <div key={exam.name} className="flex flex-col gap-4 border border-line bg-paper p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-serif text-[16px] font-medium">{exam.name}</p><p className="mt-1 text-[12px] text-ink-soft">{exam.meta}</p><p className="mt-3 font-mono text-[10px] uppercase tracking-wider text-ink-soft">{exam.date}</p></div>{exam.ready ? <Link to="/student/exam" className="border border-maroon bg-maroon px-4 py-2.5 text-center font-mono text-[10px] uppercase tracking-wider text-paper hover:bg-maroon/90">Enter exam →</Link> : <span className="border border-line px-4 py-2.5 text-center font-mono text-[10px] uppercase tracking-wider text-ink-soft">Scheduled</span>}</div>)}</div></section>
    <section className="mt-9 grid gap-4 md:grid-cols-2"><div className="border border-line p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-ink-soft">Before you begin</p><ul className="mt-4 space-y-3 text-[13px] text-ink-soft"><li>✓ Keep your ID card nearby</li><li>✓ Use a stable internet connection</li><li>✓ Allow camera and microphone access</li></ul></div><div className="border border-line p-5"><p className="font-mono text-[10px] uppercase tracking-widest text-ink-soft">Latest result</p><p className="mt-3 font-serif text-[16px]">Operating Systems</p><div className="mt-3 flex items-end justify-between"><span className="font-mono text-[11px] text-ink-soft">Published 12 Mar 2026</span><span className="font-serif text-2xl text-success">84%</span></div></div></section>
  </RoleLayout>;
}
