import type React from "react";

export function PageHeading({ eyebrow, title, detail, action }: { eyebrow: string; title: string; detail: string; action?: React.ReactNode }) { return <div className="flex flex-col justify-between gap-4 border-b border-line pb-6 md:flex-row md:items-end"><div><p className="font-mono text-[10px] uppercase tracking-widest text-soft">{eyebrow}</p><h1 className="mt-1 font-serif text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-[13px] text-soft">{detail}</p></div>{action && <div>{action}</div>}</div>; }

export function Button({ children, onClick, primary = false, disabled = false, icon, iconRight, className = "", title, size = "md", variant }: { children: React.ReactNode; onClick?: () => void; primary?: boolean; disabled?: boolean; icon?: React.ReactNode; iconRight?: React.ReactNode; className?: string; title?: string; size?: "sm" | "md" | "lg"; variant?: "primary" | "secondary" | "ghost" | "danger" | "outline" }) { const pad = size === "sm" ? "px-3 py-1.5 text-[9px]" : size === "lg" ? "px-5 py-3 text-[11px]" : "px-4 py-2.5 text-[10px]"; const kind = variant ?? (primary ? "primary" : "secondary"); const tone = disabled ? "cursor-not-allowed border-line bg-line/30 text-soft" : kind === "primary" ? "border-forest bg-forest text-paper shadow-sm hover:bg-forest-soft hover:shadow" : kind === "danger" ? "border-alert/70 bg-alert text-paper shadow-sm hover:bg-alert/90" : kind === "ghost" ? "border-transparent bg-transparent text-soft hover:bg-raised hover:text-ink" : kind === "outline" ? "border-line bg-transparent text-ink hover:border-forest hover:text-forest" : "border-line bg-raised text-ink hover:border-forest hover:text-forest"; return <button title={title} onClick={onClick} disabled={disabled} className={`inline-flex select-none items-center justify-center gap-2 border font-mono uppercase tracking-wider transition-all duration-150 focus-visible:ring-2 focus-visible:ring-forest/40 focus-visible:ring-offset-2 focus-visible:ring-offset-paper active:translate-y-px ${pad} ${tone} ${className}`}>{icon}{children}{iconRight}</button>; }

export function Field({ label, value }: { label: string; value: string }) { return <label className="text-[12px] text-soft">{label}<input value={value} readOnly className="mt-1 block w-full border border-line bg-paper px-3 py-2 text-[13px] text-ink"/></label>; }
export function Metric({ label, value, detail, tone, onClick }: { label: string; value: string; detail: string; tone: string; onClick?: () => void }) { return <div onClick={onClick} className={`border border-line bg-raised p-5 ${onClick ? "cursor-pointer hover:border-forest" : ""}`}><p className="font-mono text-[10px] uppercase tracking-widest text-soft">{label}</p><p className={`mt-2 font-serif text-3xl ${tone}`}>{value}</p><p className="mt-1 text-[12px] text-soft">{detail}</p></div>; }
export function SelectField({ label, options, value, onChange }: { label: string; options: string[]; value?: string; onChange?: (value: string) => void }) { return <label className="block text-[12px] text-soft">{label}<select value={value} onChange={(e) => onChange?.(e.target.value)} className="mt-1 block w-full border border-line bg-paper px-3 py-2.5 text-[13px] text-ink">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
