// GENERATED by frontend/scripts/edgeGrading.mjs from src/shared/domain/exam. Do not edit.
import type { DBQuestion, PaperSlot } from "./types.ts";
import { questionsForPaper, remapAnswer } from "./paperBuilder.ts";
import { isAutoGraded, questionKind } from "./questionKind.ts";
import { gradeObjective, paperTotal, round2, scoreObjective, type NegativeSettings } from "./scoring.ts";

export type AutoGradeResult = {
  /** Final paper score, or null while hand-graded questions still need marks. */
  score: number | null;
  objectiveScore: number;
  objectiveMax: number;
  max: number;
  correct: number;
  wrong: number;
  unanswered: number;
  /** Questions an evaluator must mark (descriptive / coding). */
  manual: number;
};

/** Grade the objective part of one attempt against the answer key. */
export function autoGradeAttempt(
  pool: DBQuestion[],
  paper: unknown,
  answers: Record<string, unknown>,
  settings?: NegativeSettings | null,
): AutoGradeResult {
  const slots = new Map(((Array.isArray(paper) ? paper : []) as PaperSlot[]).map((s) => [s.id, s]));
  const out: AutoGradeResult = { score: null, objectiveScore: 0, objectiveMax: 0, max: 0, correct: 0, wrong: 0, unanswered: 0, manual: 0 };
  const scores: number[] = [];
  for (const q of questionsForPaper(paper, pool)) {
    const marks = q.marks || 1;
    const kind = questionKind(q.type, q.options?.length ?? 0);
    out.max += marks;
    if (!isAutoGraded(kind)) {
      out.manual += 1;
      continue;
    }
    out.objectiveMax += marks;
    const verdict = gradeObjective(kind, q.answer, remapAnswer(slots.get(q.id), q.options, answers[q.id]));
    out[verdict] += 1;
    scores.push(scoreObjective(kind, marks, verdict, settings));
  }
  out.objectiveScore = paperTotal(scores);
  out.score = out.manual === 0 ? round2(out.objectiveScore) : null;
  return out;
}
