// GENERATED by frontend/scripts/edgeGrading.mjs from src/shared/domain/exam. Do not edit.
/** Canonical question kinds. The DB stores free-form type labels
 *  ("MCQ", "True / False", "LONG_ANSV", "mcq", …); everything that branches on
 *  question type goes through `questionKind` so the builder, the exam screen
 *  and grading always agree. */
export type QuestionKind = "mcq" | "msq" | "truefalse" | "numerical" | "subjective" | "coding";

export const QUESTION_KINDS: QuestionKind[] = ["mcq", "msq", "truefalse", "numerical", "subjective", "coding"];

export const KIND_LABEL: Record<QuestionKind, string> = {
  mcq: "MCQ",
  msq: "MSQ",
  truefalse: "True / False",
  numerical: "Numerical",
  subjective: "Descriptive",
  coding: "Coding",
};

/** Kinds graded against the answer key; the rest need manual review. */
export const AUTO_GRADED_KINDS: QuestionKind[] = ["mcq", "msq", "truefalse", "numerical"];

export function questionKind(type: string | null | undefined, optionCount = 0): QuestionKind {
  const t = (type ?? "").toLowerCase().replace(/[^a-z]/g, "");
  if (t.includes("truefalse") || t === "tf" || t === "boolean") return "truefalse";
  if (t.includes("msq") || t.includes("multi")) return "msq";
  if (t.includes("mcq") || t.includes("single")) return "mcq";
  if (t.includes("numer") || t.includes("integer")) return "numerical";
  if (t.includes("cod")) return "coding";
  if (t.includes("subj") || t.includes("long") || t.includes("desc") || t.includes("essay")) return "subjective";
  return optionCount > 0 ? "mcq" : "subjective";
}

export const isAutoGraded = (kind: QuestionKind) => AUTO_GRADED_KINDS.includes(kind);
