// GENERATED by frontend/scripts/edgeGrading.mjs from src/shared/domain/exam. Do not edit.
export type { PaperSlot } from "./paperBuilder.ts";

export type DBQuestion = {
  id: string;
  exam_id: string | null;
  title: string;
  type: string;
  unit: string | null;
  difficulty: string | null;
  marks: number;
  options: string[] | null;
  answer: string | null;
  subjective_mode?: "both" | "qr" | "textbox" | null;
};
